#!/bin/bash

echo $0
USAGE="USAGE: qsub ks_convergence_intrawalk.pbs -v ARGS=\"...\""


if [ ! -z "${PBS_O_WORKDIR+xxx}" ]; then
	cd $PBS_O_WORKDIR
fi

[[ -z ${ARGS+xxx} ]] && { echo "NO ARGS SPECIFIED!" >&2; exit 1; }

echo "ARGS: ${ARGS}"
echo "build command"
CMD="/home/kristopher.zarns/dna_at_home/scripts/ks_convergence_intrawalk.py ${ARGS}"
echo "CMD: ${CMD}"

#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:40:00
#PBS -l pmem=4gb
#PBS -j oe
echo " "
echo " "
echo "Job started on $(hostname) at $(date)"
eval "${CMD}"
echo " "
echo "Job Ended at $(date)"
echo " #"

