#!/bin/bash

echo $0
USAGE="USAGE: qsub run.pbs -v SCRIPT=\"...\""

if [ ! -z "${PBS_O_WORKDIR+xxx}" ]; then
	cd $PBS_O_WORKDIR
fi

if [ -z "${SCRIPT+xxx}" ]; then
	echo "NO SCRIPT SPECIFIED!"
	exit 1
fi
echo $SCRIPT
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00
#PBS -l pmem=1gb
#PBS -j oe
echo " "
echo " "
echo "Job started on `hostname` at `date`"
#note using eval now so redirects work
eval ${SCRIPT}
echo " "
echo "Job Ended at `date`"
echo " #"

